-- ==============================================================================
-- Sreesha Elegance — Seed Data (Catalog, Initial Coupons & Sample Reviews)
-- ==============================================================================

-- 1. SEED COUPONS
INSERT INTO public.coupons (code, discount_type, discount_value, min_order, active)
VALUES
  ('WELCOME10', 'percentage', 10, 2000, true),
  ('ROYAL15', 'percentage', 15, 10000, true),
  ('ELEGANCE2000', 'fixed', 2000, 15000, true)
ON CONFLICT (code) DO NOTHING;

-- 2. SEED PRODUCTS
INSERT INTO public.products (
  id, slug, title, category, category_label, collection, price, original_price,
  primary_image, gallery_images, badge, rating, review_count, sizes,
  fabric, weave, color, occasion, silk_mark_certified, blouse_included,
  short_description, description, details
) VALUES
(
  'saree-01',
  'kanchipuram-pure-silk-saree-emerald',
  'Kanchipuram Pure Silk Saree — Emerald & Pure Gold Zari',
  'sarees',
  'Kanchipuram Silk',
  'Royal Nizam Edit',
  18500,
  24000,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85", "https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85", "https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'BESTSELLER',
  4.9,
  38,
  '["Unstitched Blouse", "Stitched Blouse (34)", "Stitched Blouse (36)", "Stitched Blouse (38)", "Stitched Blouse (40)"]'::jsonb,
  '100% Pure Mulberry Silk',
  'Korvai Handloom',
  'Emerald Green',
  'Bridal / Reception / Festive',
  true,
  true,
  'Handwoven in temple town Kanchipuram using heritage Korvai techniques, adorned with intricate floral and peacock motifs in certified pure gold zari.',
  'A masterpiece of South Indian handloom heritage. This heirloom Kanchipuram saree boasts an opulent emerald green body paired with contrasting crimson borders laden with pure gold zari threadwork.',
  '{"origin": "Kanchipuram, Tamil Nadu / Finished at Hyderabad Atelier", "zariType": "Certified Pure Silver Electroplated Gold Zari", "sareeLength": "5.5 meters", "blouseLength": "0.8 meter matching unstitched blouse piece", "washCare": "Strictly Dry Clean Only. Store in breathable muslin cotton cloth.", "dispatchTime": "Ships in 24-48 hours. Bespoke blouse stitching takes 4-6 business days."}'::jsonb
),
(
  'saree-02',
  'banarasi-kadhwa-silk-ivory-rose',
  'Banarasi Kadhwa Brocade Saree — Ivory Cream & Rose Gold',
  'sarees',
  'Banarasi Silk',
  'Royal Nizam Edit',
  14200,
  17500,
  'https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85", "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'LIMITED',
  4.8,
  22,
  '["Unstitched Blouse", "Stitched Blouse (36)", "Stitched Blouse (38)"]'::jsonb,
  'Katan Pure Silk',
  'Handloom Kadhwa Technique',
  'Ivory Cream',
  'Sangeet / Festive / Cocktail',
  true,
  true,
  'Opulent ivory Katan silk handcrafted with traditional Kadhwa bootis in subtle rose-gold zari, finished with scalloped border detailing.',
  'An epitome of Varanasi historic weaving mastery. The delicate Kadhwa technique leaves zero loose threads on the reverse, ensuring featherlight drape and majestic sheen.',
  '{"origin": "Varanasi, Uttar Pradesh", "zariType": "Fine Rose Gold Tested Zari", "sareeLength": "5.5 meters", "blouseLength": "0.85 meter brocade blouse piece", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 24 hours"}'::jsonb
),
(
  'saree-03',
  'paithani-silk-saree-royal-purple',
  'Pure Paithani Silk Saree — Royal Purple & Peacock Pallu',
  'sarees',
  'Paithani Silk',
  'Heritage Weaves',
  22000,
  28000,
  'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85", "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'NEW',
  5.0,
  14,
  '["Unstitched Blouse", "Custom Tailored"]'::jsonb,
  'Pure Mulberry Silk',
  'Tapestry Handloom Weave',
  'Royal Purple',
  'Weddings / Festive Pheras',
  true,
  true,
  'Handcrafted with iconic kaleidoscope peacock motifs (Mor Bangadi) on a shimmering royal purple pure silk drape.',
  'Preserving the royal tradition of Maharashtra and Deccan royalty. Featuring kaleidoscopic tapestry borders and an opulent golden pallu.',
  '{"origin": "Yeola, Maharashtra", "zariType": "Pure Golden Zari", "sareeLength": "5.5 meters", "blouseLength": "0.8 meter matching silk blouse", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 48 hours"}'::jsonb
),
(
  'saree-04',
  'uppada-jamdani-silk-saree-ruby-gold',
  'Uppada Pure Silk Jamdani Saree — Ruby Red & Gold Zari',
  'sarees',
  'Uppada Silk',
  'Deccan Royal Edit',
  26500,
  32000,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'BESTSELLER',
  4.9,
  29,
  '["Unstitched Blouse", "Stitched Blouse (36)", "Stitched Blouse (38)"]'::jsonb,
  'Pure Uppada Mulberry Silk',
  'Jamdani Non-Mechanical Weave',
  'Ruby Red',
  'Bridal Muhurtham / Reception',
  true,
  true,
  'Featherlight Uppada Jamdani handloom woven with silver-gilt zari floral vines on an auspicious ruby red canvas.',
  'Renowned for its gossamer lightness and translucent luster, this pure Uppada Jamdani saree requires two master artisans working for 4 weeks per piece.',
  '{"origin": "Uppada, Andhra Pradesh", "zariType": "Tested Silver-Gilt Pure Zari", "sareeLength": "5.5 meters", "blouseLength": "0.8 meter matching blouse", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 24 hours"}'::jsonb
),
(
  'saree-05',
  'gadwal-silk-saree-maroon-mustard',
  'Handloom Gadwal Saree — Maroon & Mustard Temple Border',
  'sarees',
  'Gadwal Silk',
  'Heritage Weaves',
  16800,
  21000,
  'https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'NEW',
  4.8,
  17,
  '["Unstitched Blouse", "Stitched Blouse (36)"]'::jsonb,
  'Pure Silk with Zari Borders',
  'Kuttu Interlocked Weave',
  'Maroon & Mustard',
  'Traditional Festive / Puja',
  true,
  true,
  'Telangana pride — cotton-silk body joined seamlessly with pure silk kumbha temple borders and rich zari pallu.',
  'A classic Gadwal weave celebrated across generations in Telangana. The interlocked weft border ensures comfort and peerless grandeur.',
  '{"origin": "Jogulamba Gadwal, Telangana", "zariType": "Pure Zari", "sareeLength": "5.5 meters", "blouseLength": "0.8 meter blouse", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 24 hours"}'::jsonb
),
(
  'lehenga-01',
  'royal-nizam-bridal-lehenga-crimson',
  'Royal Nizam Bridal Lehenga — Crimson Velvet & Zardozi',
  'lehengas',
  'Bridal Lehenga',
  'Royal Nizam Edit',
  65000,
  82000,
  'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85", "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'NEW',
  5.0,
  19,
  '["Bespoke Made-to-Measure", "Size S (34)", "Size M (36)", "Size L (38)", "Size XL (40)"]'::jsonb,
  'Micro Velvet & Organza Silk',
  'Handcrafted Zardozi & Dabka',
  'Royal Crimson Red',
  'Bridal Vows / Wedding Night',
  true,
  true,
  'Hand-embroidered by Hyderabads master karigars with antique zardozi, real seed pearls, and dabka work, accompanied by double organza dupattas.',
  'An ensemble fit for a queen. Handcrafted over 320 man-hours in our Kukatpally atelier, this bridal lehenga features a flared 16-kali silhouette adorned with heritage Hyderabadi jali patterns.',
  '{"origin": "Handcrafted in Hyderabad, Telangana", "zariType": "Antique Dull Gold & Zardozi Wire", "washCare": "Specialist Luxury Dry Clean Only", "dispatchTime": "Bespoke dispatch in 10-14 days. Express alterations available."}'::jsonb
),
(
  'lehenga-02',
  'champagne-mirrorwork-festive-lehenga',
  'Champagne Gold Mirrorwork Lehenga — Silk Georgette',
  'lehengas',
  'Festive Lehenga',
  'Contemporary Glamour',
  38000,
  45000,
  'https://images.unsplash.com/photo-1585944672573-eda5af88e8af?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1585944672573-eda5af88e8af?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'BESTSELLER',
  4.9,
  26,
  '["Size S (34)", "Size M (36)", "Size L (38)"]'::jsonb,
  'Pure Viscose Silk Georgette',
  'Cutdana & Real Mirrorwork',
  'Champagne Gold',
  'Sangeet / Cocktail / Reception',
  false,
  true,
  'Twirl-ready champagne gold lehenga glittering with intricate glass mirrors, resham thread accents, and a scalloped dupatta.',
  'Crafted for modern brides and bridesmaid royalty. The mirrorwork catches the ambient night lights effortlessly while remaining lightweight and comfortable.',
  '{"origin": "Hyderabad Atelier", "zariType": "Silver Resham & Hand-cut Mirrors", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 3-5 business days"}'::jsonb
),
(
  'kurti-01',
  'anarkali-suit-set-midnight-blue',
  'Chanderi Silk Anarkali Set — Midnight Blue & Gota Patti',
  'kurtis',
  'Designer Anarkali',
  'Festive Prêt',
  8900,
  11500,
  'https://images.unsplash.com/photo-1585944672573-eda5af88e8af?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1585944672573-eda5af88e8af?auto=format&fit=crop&w=1000&q=85", "https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'SALE',
  4.7,
  42,
  '["XS (32)", "S (34)", "M (36)", "L (38)", "XL (40)", "XXL (42)"]'::jsonb,
  'Handwoven Chanderi Silk',
  'Handcrafted Gota Patti & Mukaish',
  'Midnight Blue',
  'Diwali / Festive Puja / Mehendi',
  false,
  false,
  'A flowy 3-piece Chanderi silk Anarkali set featuring artisanal Rajasthani gota patti borders, churidar pants, and a tissue organza dupatta.',
  'Elegance in motion. Cut from breezy Chanderi silk with a comfortable mulmul lining, this Anarkali is adorned with hand-stitched gota patti ribbons along the neck and hemline.',
  '{"origin": "Kukatpally Boutique Workshop", "zariType": "Lappa Gota Lace", "washCare": "Dry Clean Recommended or Gentle Handwash", "dispatchTime": "Ships in 24 hours"}'::jsonb
),
(
  'kurti-02',
  'chikankari-straight-kurta-set-powder-peach',
  'Lucknowi Mukaish Kurta Set — Powder Peach Modal Silk',
  'kurtis',
  'Kurta & Palazzo Set',
  'Boutique Daywear',
  6400,
  7800,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'NEW',
  4.9,
  18,
  '["S (34)", "M (36)", "L (38)", "XL (40)"]'::jsonb,
  'Pure Modal Silk',
  'Authentic Hand-Chikankari',
  'Powder Peach',
  'Day Festive / Family Celebrations',
  false,
  false,
  'Intricate hand-embroidered shadow work and mukaish metallic sequins on ultra-soft breathable modal silk with matching straight trousers.',
  'A soothing palette for daytime elegance. Hand-stitched by skilled women artisans with bakhiya, phanda, and keelkangan needlework.',
  '{"origin": "Lucknow & Hyderabad Collaboration", "zariType": "Mukaish Silver Dots", "washCare": "Gentle Hand Wash with Mild Liquid Detergent", "dispatchTime": "Ships in 24 hours"}'::jsonb
),
(
  'contemporary-01',
  'draped-saree-gown-emerald-velvet',
  'Ready-to-Wear Draped Saree Gown — Olive & Metallic Gold',
  'contemporary',
  'Indo-Western Couture',
  'Modern Nizam Edit',
  24500,
  29000,
  'https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1617627143233-0072f0906bea?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'BESTSELLER',
  4.8,
  31,
  '["XS (32)", "S (34)", "M (36)", "L (38)"]'::jsonb,
  'Stretch Satin Crepe & Organza',
  'Pleated Draping & Cutdana Corset',
  'Olive Gold',
  'Sangeet / Red Carpet / Reception',
  false,
  true,
  'Pre-stitched ready-to-wear draped saree with a structured pearl-encrusted corset bodice. Slip into royal elegance in under 60 seconds.',
  'No pins, no pleating stress. Designed for the globetrotting Indian woman who values heritage aesthetics without compromising modern convenience.',
  '{"origin": "Hyderabad Boutique Atelier", "zariType": "Cutdana & Crystal Wire", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 48 hours"}'::jsonb
),
(
  'contemporary-02',
  'cape-jacket-sharara-set-garnet',
  'Embroidered Cape & Sharara Set — Garnet Rose Silk',
  'contemporary',
  'Sharara & Cape Ensemble',
  'Modern Nizam Edit',
  19800,
  23500,
  'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85',
  '["https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=85"]'::jsonb,
  'NEW',
  4.9,
  16,
  '["S (34)", "M (36)", "L (38)", "XL (40)"]'::jsonb,
  'Raw Silk & Soft Tulle',
  'Zari Resham & Pearl Embroidery',
  'Garnet Rose',
  'Cocktails / Destination Weddings',
  false,
  true,
  'Flared tiered sharara pants paired with an embroidered bustier and a dramatic floor-sweeping sheer cape.',
  'Make an unforgettable entrance. The cape floats gracefully as you walk, embellished along the hemline with heritage Hyderabadi border embroidery.',
  '{"origin": "Hyderabad Atelier", "zariType": "Rose Gold Zari Threads", "washCare": "Dry Clean Only", "dispatchTime": "Ships in 3 business days"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  primary_image = EXCLUDED.primary_image,
  gallery_images = EXCLUDED.gallery_images,
  description = EXCLUDED.description,
  details = EXCLUDED.details;
